#pragma once
#include "types.h"
#include <array>
namespace tsl {
	namespace iplug {
		enum ParamFlags
		{
			FlagsNone = 0,
			FlagOneShot = 1 << 0,
			FlagPower = 1 << 1,
			FlagBypass = 1 << 2
		};

        struct DawParam
        {
            constexpr DawParam() = default;
            constexpr DawParam(int n)
                : num(n) {}
            constexpr DawParam(int n, ParamFlags f)
                : num(n), flags(f) {}
            constexpr DawParam(int n, ParamFlags f, int o)
                : num(n), flags(f), offset(o) {}

            int num{}, offset{};
            ParamFlags flags{ FlagsNone };
        };

#ifdef GRAINSTORM
        constexpr DawParam dp[] =
        {
            POWERTRACK,
            DISTRSOURCE,
            PREGAIN,
            POSTGAIN,
            SPEED,
            GRAINSIZE,
            DENSITY,
            RNDREAD,
            GRAINPAN,
            AWINCYLCES,
            ENVPHASE,
            PITCH,
            GRAINGLISS,
            REVERSEGRAINS,
            BANDLIMITEDGRAINENV,
            NOINPUTFROMTRACK,
            INTEGERENVCYCLES,
            DOWSOLA,
            HQ_RESAMPLING,
            ASGRAINGEN,
            GRAINGENMONO,
            ARP_SWING,
            RNDWRITE,
            {GRAINGENLOOP},
            {GRAINGENREST},
            {GRAINGENHEIGHTA},
            {GRAINGENHEIGHTB},
            {GRAINGENSPLINECPSA},
            {GRAINGENSPLINECPSB},
            {GRAINGENSPLINEDENSA},
            {GRAINGENSPLINEDENSB},
            {GRAINGENFOLATTACK},
            {GRAINGENFOLDECAY},
            {GRAINGENFOLGAIN},
            {GRAINGENFOLDENSA},
            {GRAINGENFOLDENSB},
            // Takes one of the reserved slots, so no existing automation id moves.
            {GRAINGENVEL},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {GRAINSEQSTEPS},
            {GRAINS},
            {SILENCE},
            {OFFGRAIN, FlagPower, SPACE_ARP},
            {ARP_INTERVAL},
            {ARP_CYCLES},
            {ARP_CYCLEMODE},
            {OFFGRAIN, FlagPower, SPACE_PITCH},
            SEMITONES,
            {SEMITONES_MIN},
            {SEMITONES_MAX},
            {PITCHMIN},
            {PITCHMAX},
            {BYPASSGRAINFX, FlagBypass, SPACE_GRAINPART},
            {OFFGRAIN, FlagPower, SPACE_GRAINPART},
            {GRAINPARTNUMPART},
            {GRAINPARTOFFSET},
            {GRAINPARTFREQ},
            {GRAINPARTMULTI},
            {GRAINPARTFOLLOW},
            {GRAINPARTHOLD},
            {GRAINPARTDRY},
            {GRAINPARTWET},
            {BYPASSGRAINFX, FlagBypass, SPACE_GRAINMODAL},
            {OFFGRAIN, FlagPower, SPACE_GRAINMODAL},
            {GRAINMODALINGAIN},
            {GRAINMODALPREGAIN},
            {GRAINMODALFREQ},
            {GRAINMODALQ},
            {GRAINMODALMODE},
            {GRAINMODALHOLD},
            {GRAINMODALFOLLOW},
            {GRAINMODALDRY},
            {GRAINMODALWET},
            {BYPASSGRAINFX, FlagBypass, SPACE_GRAINVCO},
            {OFFGRAIN, FlagPower, SPACE_GRAINVCO},
            {GRAINVCO1POW},
            {GRAINVCO0WAVEFORM},
            {GRAINVCO1PW},
            {GRAINVCO1DET},
            {GRAINVCO1AMP},
            {GRAINVCO2POW},
            {GRAINVCO1WAVEFORM},
            {GRAINVCO2PW},
            {GRAINVCO2DET},
            {GRAINVCO2AMP},
            {GRAINVCO3POW},
            {GRAINVCO2WAVEFORM},
            {GRAINVCO3PW},
            {GRAINVCO3DET},
            {GRAINVCO3AMP},
            {GRAINVCOPHRESET},
            {GRAINVCOVCF},
            {GRAINVCOCPS},
            {GRAINVCODETLR},
            {GRAINVCOFOLLOW},
            {GRAINVCOHOLD},
            {GRAINVCODRY},
            {GRAINVCOWET},
            {BYPASSGRAINFX, FlagBypass, SPACE_GRAINFILTER},
            {OFFGRAIN, FlagPower, SPACE_GRAINFILTER},
            {GRAINFILTERRES},
            GRAINFILTERTYPE,
            GRAINFILTERGAIN,
            {BYPASSGRAINFX, FlagBypass, NOISEGRAINEFFECT},
            {OFFGRAIN, FlagPower, NOISEGRAINEFFECT},
            {NOISEGRAINTYPE},
            {NOISEGRAINMIX},
            NOISEGRAINGAIN,
            {BYPASSGRAINFX, FlagBypass, SPACE_GRAIN_BP},
            {OFFGRAIN, FlagPower, SPACE_GRAIN_BP},
            {GRAINBPCENTERMIN},
            {GRAINBPCENTERMAX},
            {GRAINBPBWMIN},
            {GRAINBPBWMAX},
            {GRAINBPMIX},
            GRAINBPGAIN,
            {BYPASSGRAINFX, FlagBypass, SPACE_RM_GRAIN},
            {OFFGRAIN, FlagPower, SPACE_RM_GRAIN},
            {GRAINRMMIN},
            {GRAINRMMAX},
            {GRAINRMMIX},
            {BYPASSGRAINFX, FlagBypass, SPACE_GRAINREVERB},
            {OFFGRAIN, FlagPower, SPACE_GRAINREVERB},
            {GRAINREVERBDECAY},
            {GRAINREVERBMIX},
            {GRAINREVERBGAIN},
            {BYPASSGRAINFX, FlagBypass, SPACE_PDETECTGRAIN},
            {OFFGRAIN, FlagPower, SPACE_PDETECTGRAIN},
            {PDETECTGRAINSMOOTH2},
            {PDETECTGRAINPRELP},
            {PDETECTGRAINA},
            {PDETECTGRAINB},
            {PDETECTGRAINTRANSPOSE},
            { FFT_SIZE },
            {OFFGRAIN, FlagPower, SPACE_PV_MAIN},
            {ASPV},
            {CUTSTRETCH},
            {STRETCHCOEFF},
            {PVAMPS2PHASE},
            {PVAMPS2RANGE},
            {PVAMPS2DRY},
            {PVAMPS2WET},
            {PVSPECBOUNDAIN},
            {PVSPECBOUNDBIN},
            {PVSPECBOUNDAOUT},
            {PVSPECBOUNDBOUT},
            {PVSPECINV},
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            {OFFGRAIN, FlagPower, SPACE_CROSS_MAIN},
            {ASCROSS},
            {CROSS_MAG},
            {CROSS_PHASE},
            {CROSSCEP1CUTMOD},
            {CROSSCEP2CUTSRC},
            {CROSSCEP2CUTMOD},
            {CROSSINTCUTMOD},
            {CROSSINTCUTSRC},
            {IPOL},
            {VOC2CHANS},
            {VOC2HP},
            { CROSSCEP1EMPH },
            {CROSSLPCORDER},
            {CROSSLPCW},
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            {OFFGRAIN, FlagPower, SPACE_LOOPER},
            {LOOPERFADE},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {ENVINNER},
            {ENVOUTER},
            {AOUTERCYCLES},
            {AOUTERDEPTH},
            {ENVINNER2},
            {ENVOUTER2},
            {AOUTERCYCLES2},
            {AOUTERDEPTH2},
            {GRAINENVINTERPOL},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            { PARAM_NOT_ASSIGNED },
            {LFO1POWER},
            {LFO1CPS},
            LFO1CURVE,
            LFO1CPSMIN,
            LFO1CPSMAX,
                LFO1RNDDEPTH,
                LFO1RNDCURVE,
                LFO1RNDTYPE,
                LFO1RNDBETA,
                LFO1RNDALPHA,
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            {LFO2POWER},
            {LFO2CPS},
            LFO2CURVE,
            LFO2CPSMIN,
            LFO2CPSMAX,
            LFO2RNDDEPTH,
            LFO2RNDCURVE,
            LFO2RNDTYPE,
            LFO2RNDBETA,
            LFO2RNDALPHA,
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            { PARAM_NOT_ASSIGNED },
            {LFO3POWER},
            {LFO3CPS},
            LFO3CURVE,
            LFO3CPSMIN,
            LFO3CPSMAX,
            LFO3RNDDEPTH,
            LFO3RNDCURVE,
            LFO3RNDTYPE,
            LFO3RNDBETA,
            LFO3RNDALPHA,
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {BYPASSFX, FlagBypass, SPACE_SHIFTER},
            {OFFFX, FlagPower, SPACE_SHIFTER},
            {PITCHSHIFTMODE},
            { PITCHSHIFTSHIFT },
            {PITCHSHIFERMIX},
            {BYPASSFX, FlagBypass, SPACE_SSB},
            { OFFFX, FlagPower, SPACE_SSB },
            { SSBMODTYPE },
            { SSBMODRATE },
            { SSBMODMIX },
            { BYPASSFX, FlagBypass, SPACE_PHASER },
            { OFFFX, FlagPower, SPACE_PHASER },
            { PHASERFB },
            { PHASERNOTCHES },
            { PHASERBAND },
            { PHASERMIX },
            { BYPASSFX, FlagBypass, SPACE_PHASER4 },
            { OFFFX, FlagPower, SPACE_PHASER4 },
            { PHASER4BAND },
            { PHASER4STAGES },
            { PHASER4SPACING },
            { PHASER4RADIUS },
            { PHASER4FB },
            { PHASER4MIX },
            { BYPASSFX, FlagBypass, SPACE_FLANGER },
            { OFFFX, FlagPower, SPACE_FLANGER },
            { FLANGERDELAY },
            { FLANGERFB },
            { FLANGERMIX },
            { FLANGERGAIN },
            { BYPASSFX, FlagBypass, SPACE_DELAY },
            { OFFFX, FlagPower, SPACE_DELAY },
            { DELAYHOLD },
            { DELAYBACKW },
            { DELAYDEL },
            { DELAYFB },
            { DELAYSHIFT2 },
            { DELAYSHIFTMIX },
            { DELAYHP },
            { DELAYLP },
            { DELAYDRY },
            { DELAYWET },
            { BYPASSFX, FlagBypass, SPACE_MDELAY },
            { OFFFX, FlagPower, SPACE_MDELAY },
            { MDELAYMIX },
            { MDELAYGAIN },
            { MDELAY_MODE },
            MDELAY1HOLD,
            MDELAY1BACKW,
            MDELAY1DEL,
            MDELAY1FB,
			MDELAY1HP,
			MDELAY1LP,
            MDELAY1GAIN,
            MDELAY2HOLD,
            MDELAY2BACKW,
            MDELAY2DEL,
            MDELAY2FB,
            MDELAY2HP,
            MDELAY2LP,
            MDELAY2GAIN,
            MDELAY3HOLD,
            MDELAY3BACKW,
            MDELAY3DEL,
            MDELAY3FB,
            MDELAY3HP,
            MDELAY3LP,
            MDELAY3GAIN,
            MDELAY4HOLD,
            MDELAY4BACKW,
            MDELAY4DEL,
            MDELAY4FB,
            MDELAY4HP,
            MDELAY4LP,
            MDELAY4GAIN,
            MDELAY5HOLD,
            MDELAY5BACKW,
            MDELAY5DEL,
            MDELAY5FB,
            MDELAY5HP,
            MDELAY5LP,
            MDELAY5GAIN,
            MDELAY6HOLD,
            MDELAY6BACKW,
            MDELAY6DEL,
            MDELAY6FB,
            MDELAY6HP,
            MDELAY6LP,
            MDELAY6GAIN,
            MDELAY7HOLD,
            MDELAY7BACKW,
            MDELAY7DEL,
            MDELAY7FB,
            MDELAY7HP,
            MDELAY7LP,
            MDELAY7GAIN,
            MDELAY8HOLD,
            MDELAY8BACKW,
            MDELAY8DEL,
            MDELAY8FB,
            MDELAY8HP,
            MDELAY8LP,
            MDELAY8GAIN,
            { BYPASSFX, FlagBypass, SPACE_DISTORT },
            { OFFFX, FlagPower, SPACE_DISTORT },
            { DISTTONE },
            { DISTDRIVE },
            { DISTMIX },
            { DISTGAIN },
            { BYPASSFX, FlagBypass, SPACE_BITCRUSHER },
            { OFFFX, FlagPower, SPACE_BITCRUSHER },
            { BCSR },
            { BCBITS },
            { BCTONE },
            { BCMIX },
            { BCGAIN },
            { BYPASSFX, FlagBypass, SPACE_SATURATOR },
            { OFFFX, FlagPower, SPACE_SATURATOR },
            { SATDRIVE },
            { SATWET },
            { SATDRY },
            { BYPASSFX, FlagBypass, SPACE_VOCODER },
            { OFFFX, FlagPower, SPACE_VOCODER },
            { VOCBW },
            { VOCA },
            { VOCB },
            { VOCCHANS },
            { VOCATT },
            { VOCREL },
            { VOCMIX },
            { VOCGAIN },
            { BYPASSFX, FlagBypass, SPACE_LPCVOCODER },
            { OFFFX, FlagPower, SPACE_LPCVOCODER },
            { LPCVOCORDER },
            { LPCVOCWHITE },
            { LPCVOCMIX },
            { LPCVOCGAIN },
            { BYPASSFX, FlagBypass, SPACE_SPECTRAL_FILTER },
            { OFFFX, FlagPower, SPACE_SPECTRAL_FILTER },
            { SPECFILTMAGLPCUT2 },
            { SPECFILTFREQLPCUT2 },
            { SPECFILTRES },
            { SPECFILTDRY },
            { SPECFILTWET },
            { BYPASSFX, FlagBypass, SPACE_SPECDEL2 },
            { OFFFX, FlagPower, SPACE_SPECDEL2 },
            { SPECDEL2RND },
            { SPECDEL2DEL },
            { SPECDEL2FB },
            { SPECDEL2MIX },
            { SPECDEL2GAIN },
            { BYPASSFX, FlagBypass, SPACE_PVAMPS },
            { OFFFX, FlagPower, SPACE_PVAMPS },
            { PVAMPSRANGE },
            { PVAMPSBOUNDA },
            { PVAMPSBOUNDB },
            PVAMPSVCOWAVEFORM,
            PVAMPSPHASE,
            // A host's parameter index is this array's position, so inserting
            // here renumbers everything below. Fine while the plugin is
            // unreleased; once it ships, substitute in place or claim one of the
            // PARAM_NOT_ASSIGNED slots instead.
            {PVAMPSROUTE},
            {PVAMPSSMOOTH2},
            {PVAMPSDRY},
            {PVAMPSWET},
            {BYPASSFX, FlagBypass, SPACE_FM},
            {OFFFX, FlagPower, SPACE_FM},
            {FMCPS},
            {FMDETUNE},
            {FMI},
            {FMR},
            {FMRATIO},
            {FMVIBRATEA},
            {FMVIBDEPTHA},
            {FMDETLR},
            {FMFOLLOW},
            {FMHOLD},
            {FMDRY},
            {FMWET},
            {FMPOW0},
            {FMTYPE0},
            {FMSEM0},
            {FMGAIN0},
            {FMPOW1},
            {FMTYPE1},
            {FMSEM1},
            {FMGAIN1},
            {FMPOW2},
            {FMTYPE2},
            {FMSEM2},
            {FMGAIN2},
            {FMPOW3},
            {FMTYPE3},
            {FMSEM3},
            {FMGAIN3},
            {FMPOW4},
            {FMTYPE4},
            {FMSEM4},
            {FMGAIN4},
            {FMPOW5},
            {FMTYPE5},
            {FMSEM5},
            {FMGAIN5},
            {BYPASSFX, FlagBypass, SPACE_BOWED},
            {OFFFX, FlagPower, SPACE_BOWED},
            {BOWEDCPS},
            {BOWEDPOS},
            {BOWEDFOLLOW},
            {BOWEDHOLD},
            {BOWEDDRY},
            {BOWEDWET},
            {BYPASSFX, FlagBypass, NOISEMONOEFFECT},
            {OFFFX, FlagPower, NOISEMONOEFFECT},
            {NOISEMONOTYPE},
            {NOISEMONOMIX},
            {NOISEMONOGAIN},
            {BYPASSFX, FlagBypass, SPACE_MODAL},
            {OFFFX, FlagPower, SPACE_MODAL},
            {MODALFREQ},
            {MODALQ},
            {MODALMODE},
            {MODALFOLLOW},
            {MODALHOLD},
            {MODALDRY},
            {MODALWET},
            {BYPASSFX, FlagBypass, SPACE_BANDPASS},
            {OFFFX, FlagPower, SPACE_BANDPASS},
            {BPCENTER},
            {BPBW},
            {BPMIX},
            {BPGAIN},
            {BYPASSFX, FlagBypass, SPACE_MOOGLADDER},
            {OFFFX, FlagPower, SPACE_MOOGLADDER},
            {MOOGCUT},
            {MOOGRES},
            {MOOGMIX},
            {MOOGGAIN},
            {BRCENTER},
            {BYPASSFX, FlagBypass, SPACE_BANDREJECT},
            {OFFFX, FlagPower, SPACE_BANDREJECT},
            {BRBW},
            {BRMIX},
            {BRGAIN},
            {BYPASSFX, FlagBypass, SPACE_HPLP},
            {OFFFX, FlagPower, SPACE_HPLP},
            {LPHPHPCUT},
            {LPHPLPCUT},
            {LPHPMIX},
            {LPHPGAIN},
            {BYPASSFX, FlagBypass, SPACE_EQ},
            {OFFFX, FlagPower, SPACE_EQ},
            {EQ10_0},
            {EQ10_0 + 1},
            {EQ10_0 + 2},
            {EQ10_0 + 3},
            {EQ10_0 + 4},
            {EQ10_0 + 5},
            {EQ10_0 + 6},
            {EQ10_0 + 7},
            {EQ10_0 + 8},
            {EQ10_0 + 9},
            // EQ10_Q is EQ10_0 + 10 and EQ10_GAIN is EQ10_0 + 11, so listing the
            // band range up to +11 as well bound two host params to each of them:
            // automating one left the other's IParam permanently stale.
            EQ10_Q,
			EQ10_GAIN,
            {BYPASSFX, FlagBypass, SPACE_EQ5},
            {OFFFX, FlagPower, SPACE_EQ5},
            {EQ5GAIN},
            {BYPASSFX, FlagBypass, SPACE_CONVOLVER},
            {OFFFX, FlagPower, SPACE_CONVOLVER},
            {CREVMIX},
            {CREVGAIN},
            // CREVERB2 - same effect instance, no bypass/power of its own
            {CREVMORPHRATE},
            {CREVMORPHFRONT},
            {CREVMORPHREV},
            {CREVNORM},
            {CREVAUTO},
            {BYPASSFX, FlagBypass, SPACE_SPECDEL},
            {OFFFX, FlagPower, SPACE_SPECDEL},
            {SPECDELMODE},
            {SPECDELDEL},
            {SPECDELBOUNDA},
            {SPECDELBOUNDB},
            {SPECDELMIX},
            {SPECDELGAIN},
            {BYPASSFX, FlagBypass, SPACE_COMPRESSION},
            {OFFFX, FlagPower, SPACE_COMPRESSION},
            {COMPTHR},
            {COMPRATIO},
            {COMPKNEE},
            {COMPATT},
            {COMPREL},
            {COMPRMS},
            {COMPLOOKA},
            {COMPMAKE},
            {MONOCOMPSRC},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {BYPASSSTEREOFX, FlagBypass, SPACE_CHORUS},
            {OFFSTEREOFX, FlagPower, SPACE_CHORUS},
            {CHORUSINT},
            {CHORUS2RATE},
            {CHORUS2TAPS},
            {CHORUS2WIDTH},
            {CHORUSPHASE},
            {CHORUSMOD},
            {CHORUSDELAY},
            {CHORUSMIX},
            {CHORUSGAIN},
            {BYPASSSTEREOFX, FlagBypass, SPACE_PINGPONG},
            {OFFSTEREOFX, FlagPower, SPACE_PINGPONG},
            {PPHOLD},
            {PPREVERSE},
            {PPDELAY},
            {PPFB},
            {PPSHIFT},
            {PPSHIFTMIX},
            {PPHP},
            {PPLP},
            {PPDRY},
            {PPWET},
            {BYPASSSTEREOFX, FlagBypass, SPACE_REVERB1},
            {OFFSTEREOFX, FlagPower, SPACE_REVERB1},
            {REV1T60},
            {REV1DAMP},
            {REV1MIX},
            {REV1GAIN},
            {BYPASSSTEREOFX, FlagBypass, SPACE_REVERB2},
            {OFFSTEREOFX, FlagPower, SPACE_REVERB2},
            {REV2T60},
            {REV2MIX},
            {REV2GAIN},
            {BYPASSSTEREOFX, FlagBypass, SPACE_REVERB3},
            {OFFSTEREOFX, FlagPower, SPACE_REVERB3},
            {REV3REF},
            {REV3HPCUT},
            {REV3LPCUT},
            {REV3PREDELAY},
            {REV3MIX},
            {REV3GAIN},
            {BYPASSSTEREOFX, FlagBypass, SPACE_REVERB4},
            {OFFSTEREOFX, FlagPower, SPACE_REVERB4},
            {REV4REF},
            {REV4HPCUT},
            {REV4LPCUT},
            {REV4PREDELAY},
            {REV4MIX},
            {REV4GAIN},
            {BYPASSSTEREOFX, FlagBypass, SPACE_REVERB5},
            {OFFSTEREOFX, FlagPower, SPACE_REVERB5},
            {REV5PREDELAY},
            {REV5T60LOW},
            {REV5T60HI},
            {REV5XOVER},
            {REV5DAMP2},
            {REVERB5MIX},
            {REVERB5GAIN},
            {BYPASSSTEREOFX, FlagBypass, SPACE_REVERB6},
            {OFFSTEREOFX, FlagPower, SPACE_REVERB6},
            {SHIMMERDARKMODE},
            {REV7SIZE},
            {REV7FB},
            {REV7DIFF},
            {REV7HPCUT},
            {REV7LPCUT},
            {REV7RATE},
            {REV7DEPTH},
            {REV7SHIFT},
            {REV7SHIFTMODE},
            {REV7MIX},
            {REV7GAIN},
            {BYPASSSTEREOFX, FlagBypass, SPACE_MODALREV},
            {OFFSTEREOFX, FlagPower, SPACE_MODALREV},
            {MODALREVMODES},
            {MODALREVHOLD},
            {MODALREVDELAY},
            {MODALREVPITCH},
            {MODALREVWIDTH},
            {MODALREVDRY},
            {MODALREVWET},
            {BYPASSSTEREOFX, FlagBypass, SPACE_STC},
            {OFFSTEREOFX, FlagPower, SPACE_STC},
            {STCOMPTHR},
            {STCOMPRATIO},
            {STCOMPKNEE},
            {STCOMPATT},
            {STCOMPDEC},
            {STCOMPRMS},
            {STCOMPLOOKA},
            {STCOMPMAKE},
            {BYPASSSTEREOFX, FlagBypass, SPACE_LIMITER},
            {OFFSTEREOFX, FlagPower, SPACE_LIMITER},
            {LIMTHRES},
            {LIMREL},
            {BYPASSSTEREOFX, FlagBypass, SPACE_CLIPPER},
            {OFFSTEREOFX, FlagPower, SPACE_CLIPPER},
            {CLIPPERTHRS},
            {CLIPPERSTART},
            {BYPASSSTEREOFX, FlagBypass, SPACE_MONOSTEREO},
            {OFFSTEREOFX, FlagPower, SPACE_MONOSTEREO},
            {STEREOWIDTH},
            // taken from the reserved pool rather than appended next to the
            // other LPCVOC entries, so existing DAW automation indices don't shift
            {LPCVOCEMPH},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
        };
#elif defined(POCKETANALOG)
        // REBUILT 2026-08-17 (audit H6/M7/M13). No host version has shipped, so the
        // map was laid out fresh rather than patched around the reserved slots.
        // ORDER IS THE UI ORDER — pages as the tab bar presents them (GEN, EG, OSC1,
        // OSC2, SUB, NOISE, FILT, LFO, SEQ, FX, RTE), controls within a page as they
        // appear — because this order is the DAW's parameter list. From here on this
        // array is append/reserve-only again: a host index is forever once released.
        //
        // Deliberately ABSENT (do not re-add without wiring them first): the dead
        // set — EG5*, FILTGAIN, FILTCENTER, VCO3COARSE (SUB uses VCO3COARSEST),
        // VCO3SYNC (write-only _sync[2]), CDELMODE, SEQ_MODE, PADBW/BWSC/STR/SEED
        // (PAD_FIXED_* constants now), and every REV3/REV4 cut/predelay id (only
        // Progenitor1Dark is instantiated, which binds REV3GAIN/MIX/REF/DAMP) —
        // plus all NoAssignment UI/transient params (buttons, spaces, handshakes).
        constexpr DawParam dp[] =
        {
            // ── GEN ──  JITTERA/JITTERB have no knob but the engine reads them;
            // they belong beside the JITTERCENTS knob that scales them.
            POSTGAIN, JITTERCENTS, JITTERA, JITTERB,
            // ── EG ──  the UI pages one knob set through EG1..EG4; EG5 is unwired.
            EG1ATTACK, EG1DECAY, EG1SUSTAIN, EG1RELEASE,
            EG2ATTACK, EG2DECAY, EG2SUSTAIN, EG2RELEASE,
            EG3ATTACK, EG3DECAY, EG3SUSTAIN, EG3RELEASE,
            EG4ATTACK, EG4DECAY, EG4SUSTAIN, EG4RELEASE,
            // ── OSC1 ──  sub-pages OSC, PWM, WT, UNI, MODAL, PAD. PWMODSRC also
            // appears on the WT page as MRPH EG — one lane serves both.
            VCO1TYPE, VCO1EG, VCO1GAIN, VCO1COARSE, VCO1FINE, VCO1TUNEEG, VCO1SYNC,
            VCO1PW, VCO1PWMODSRC, VCO1PWMODDEPTH,
            VCO1WTSEL, VCO1WTPOS, VCO1MORPHTO, VCO1WARPTYPE, VCO1WARPEG, VCO1WARPAMT, VCO1WARPTO,
            VCO1UNIVOICES, VCO1UNIDETUNE, VCO1UNIBLEND,
            VCO1MODALCH, VCO1MODALDEC, VCO1MODALBRT, VCO1MODALHRD, VCO1MODALPOS,
#if PA_ENABLE_PAD
            VCO1PADSEL, VCO1PADMEG, VCO1PADPOS, VCO1PADMTO,
#endif
            // ── OSC2 ──
            VCO2TYPE, VCO2EG, VCO2GAIN, VCO2COARSE, VCO2FINE, VCO2TUNEEG, VCO2SYNC,
            VCO2PW, VCO2PWMODSRC, VCO2PWMODDEPTH,
            VCO2WTSEL, VCO2WTPOS, VCO2MORPHTO, VCO2WARPTYPE, VCO2WARPEG, VCO2WARPAMT, VCO2WARPTO,
            VCO2UNIVOICES, VCO2UNIDETUNE, VCO2UNIBLEND,
            VCO2MODALCH, VCO2MODALDEC, VCO2MODALBRT, VCO2MODALHRD, VCO2MODALPOS,
#if PA_ENABLE_PAD
            VCO2PADSEL, VCO2PADMEG, VCO2PADPOS, VCO2PADMTO,
#endif
            // ── SUB ──  sub-pages OSC, PWM, MOD, WT, UNI, MODAL, PAD. COARSEST is
            // the SUB's coarse; it has no SYNC.
            VCO3TYPE, VCO3EG, VCO3GAIN, VCO3COARSEST, VCO3FINE, VCO3TUNEEG,
            VCO3PW, VCO3PWMODSRC, VCO3PWMODDEPTH,
            VCO3NORMAL, VCO3RINGMOD, VCO3AM, VCO3PM, VCO3AMDEPTH, VCO3PMDEPTH,
            VCO3WTSEL, VCO3WTPOS, VCO3MORPHTO, VCO3WARPTYPE, VCO3WARPEG, VCO3WARPAMT, VCO3WARPTO,
            VCO3UNIVOICES, VCO3UNIDETUNE, VCO3UNIBLEND,
            VCO3MODALCH, VCO3MODALDEC, VCO3MODALBRT, VCO3MODALHRD, VCO3MODALPOS,
#if PA_ENABLE_PAD
            VCO3PADSEL, VCO3PADMEG, VCO3PADPOS, VCO3PADMTO,
#endif
            // ── NOISE ──
            NOISEMODE, NOISEEG, NOISEGAIN,
            // ── FILT ──
            FILT_MODE, FILTEG, RESEG, FILT_CUT, FILTRES, FILTMODALBODY, FILTMODALPOS,
            // ── LFO ──
            LFO1RATE, LFO1DEPTH, LFO1PHASE, LFO1WAVE, LFO1DEST,
            LFO2RATE, LFO2DEPTH, LFO2PHASE, LFO2WAVE, LFO2DEST,
            // ── SEQ / ARP ──
            SEQ_BPM, SEQ_SWING, SEQ_STEPS, SEQ_GAIN, SEQ_SYNCDAW, SEQ_TIMEDIV,
            ARP_MODE, ARP_STEPS,
            ARPSTEP01, ARPSTEP02, ARPSTEP03, ARPSTEP04, ARPSTEP05, ARPSTEP06, ARPSTEP07, ARPSTEP08,
            ARPSTEP09, ARPSTEP10, ARPSTEP11, ARPSTEP12, ARPSTEP13, ARPSTEP14, ARPSTEP15, ARPSTEP16,
            ARPSTEP17, ARPSTEP18, ARPSTEP19, ARPSTEP20, ARPSTEP21, ARPSTEP22, ARPSTEP23, ARPSTEP24,
            ARPSTEP25, ARPSTEP26, ARPSTEP27, ARPSTEP28, ARPSTEP29, ARPSTEP30, ARPSTEP31, ARPSTEP32,
            // ── FX ──  PHASER, DELAY, REVERB — the FX tab order.
            PHASERPOW, PHASERRANGE, PHASERFB, PHASERRATE,
            CDELPOW, CDELDEL, CDELFB, CDDELMODRATE, CDDELMODDEPTH, CDELMIX,
            REVPOW, REV3REF, REV3DAMP, REV3MIX, REV3GAIN,
            // ── RTE ──  VEL, AT, MW, KEY — the route tab order.
            VEL_TO_FILT, VEL_TO_AMP, VEL_TO_RES,
            AT_TO_FILT, AT_TO_AMP, AT_TO_VIBRATO, AT_TO_RES, AT_TO_LFORATE, AT_TO_LFODEPTH,
            AT_TO_WARP, AT_TO_MORPH, AT_TO_UNI, AT_TO_DECAY,
            MW_TO_FILT, MW_TO_VIBRATO, MW_TO_RES, MW_TO_LFORATE, MW_TO_LFODEPTH,
            MW_TO_MORPH, MW_TO_WARP, MW_TO_UNI, MW_TO_DECAY,
            KEYTRACK_TO_FILT, KEYTRACK_TO_DECAY,
            // ── LFO3 / LFO4 ──  claimed from the reserve block 2026-08-18; same
            // layout as LFO1/2 above.
            LFO3RATE, LFO3DEPTH, LFO3PHASE, LFO3WAVE, LFO3DEST,
            LFO4RATE, LFO4DEPTH, LFO4PHASE, LFO4WAVE, LFO4DEST,
            // ── reserved for future params ──  claim from the top; never insert
            // above, never reorder.
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            {PARAM_NOT_ASSIGNED},
            // ── LFO multi-dest matrix ──  4 LFOs x 21 dests, appended AFTER the
            // remaining reserves so future claims keep their indices. Host names
            // come from the per-dest param names ("PITCH".."NOISE", category LFOn).
            LFO_MD_FIRST +  0, LFO_MD_FIRST +  1, LFO_MD_FIRST +  2, LFO_MD_FIRST +  3, LFO_MD_FIRST +  4, LFO_MD_FIRST +  5, LFO_MD_FIRST +  6,
            LFO_MD_FIRST +  7, LFO_MD_FIRST +  8, LFO_MD_FIRST +  9, LFO_MD_FIRST + 10, LFO_MD_FIRST + 11, LFO_MD_FIRST + 12, LFO_MD_FIRST + 13,
            LFO_MD_FIRST + 14, LFO_MD_FIRST + 15, LFO_MD_FIRST + 16, LFO_MD_FIRST + 17, LFO_MD_FIRST + 18, LFO_MD_FIRST + 19, LFO_MD_FIRST + 20,
            LFO_MD_FIRST + 21, LFO_MD_FIRST + 22, LFO_MD_FIRST + 23, LFO_MD_FIRST + 24, LFO_MD_FIRST + 25, LFO_MD_FIRST + 26, LFO_MD_FIRST + 27,
            LFO_MD_FIRST + 28, LFO_MD_FIRST + 29, LFO_MD_FIRST + 30, LFO_MD_FIRST + 31, LFO_MD_FIRST + 32, LFO_MD_FIRST + 33, LFO_MD_FIRST + 34,
            LFO_MD_FIRST + 35, LFO_MD_FIRST + 36, LFO_MD_FIRST + 37, LFO_MD_FIRST + 38, LFO_MD_FIRST + 39, LFO_MD_FIRST + 40, LFO_MD_FIRST + 41,
            LFO_MD_FIRST + 42, LFO_MD_FIRST + 43, LFO_MD_FIRST + 44, LFO_MD_FIRST + 45, LFO_MD_FIRST + 46, LFO_MD_FIRST + 47, LFO_MD_FIRST + 48,
            LFO_MD_FIRST + 49, LFO_MD_FIRST + 50, LFO_MD_FIRST + 51, LFO_MD_FIRST + 52, LFO_MD_FIRST + 53, LFO_MD_FIRST + 54, LFO_MD_FIRST + 55,
            LFO_MD_FIRST + 56, LFO_MD_FIRST + 57, LFO_MD_FIRST + 58, LFO_MD_FIRST + 59, LFO_MD_FIRST + 60, LFO_MD_FIRST + 61, LFO_MD_FIRST + 62,
            LFO_MD_FIRST + 63, LFO_MD_FIRST + 64, LFO_MD_FIRST + 65, LFO_MD_FIRST + 66, LFO_MD_FIRST + 67, LFO_MD_FIRST + 68, LFO_MD_FIRST + 69,
            LFO_MD_FIRST + 70, LFO_MD_FIRST + 71, LFO_MD_FIRST + 72, LFO_MD_FIRST + 73, LFO_MD_FIRST + 74, LFO_MD_FIRST + 75, LFO_MD_FIRST + 76,
            LFO_MD_FIRST + 77, LFO_MD_FIRST + 78, LFO_MD_FIRST + 79, LFO_MD_FIRST + 80, LFO_MD_FIRST + 81, LFO_MD_FIRST + 82, LFO_MD_FIRST + 83,
        };
#elif defined(GENERATIVE)
        // Nothing exposed to the host yet. One reserved slot keeps dp[] a valid
        // non-empty array; the wrapper turns PARAM_NOT_ASSIGNED into a hidden
        // "Reserved" param. Real params get appended here as they are added.
        constexpr DawParam dp[] =
        {
            {PARAM_NOT_ASSIGNED},
        };
#endif
        constexpr int paramCount = sizeof(dp) / sizeof(DawParam);
#if (defined STANDALONE_MODE || defined PLUGIN_MODE) && defined(GRAINSTORM)
        constexpr auto buildPowerParams() {
            std::array<int, NUM_PARAMSPACES> result{};
            result.fill(-1);
            for (int i = 0; i < paramCount; ++i)
                if (dp[i].flags & FlagPower)
                    result[dp[i].offset] = i;
            return result;
        }

        constexpr auto buildBypassParams() {
            std::array<int, NUM_PARAMSPACES> result{};
            result.fill(-1);
            for (int i = 0; i < paramCount; ++i)
                if (dp[i].flags & FlagBypass)
                    result[dp[i].offset] = i;
            return result;
        }

        constexpr auto PowerParams = buildPowerParams();
        constexpr auto BypassParams = buildBypassParams();
#endif
	}
}
