#!/usr/bin/env python3
"""Generate the VOLTAIC Android launcher icons.

Source of truth is the baked mark in CPP-New/va/icon_voltaic.cpp -- the same
bytes the app itself draws (tsl::app::icon_data) -- so the launcher icon can
never drift from the splash animation or the in-app logo. Do not point this at a
loose PNG.

Writes, under app/src/main/res/:
  mipmap-<density>/ic_launcher.png             legacy square, mark on opaque black
  mipmap-<density>/ic_launcher_round.png       legacy round, same art circle-masked
  mipmap-<density>/ic_launcher_foreground.png  adaptive foreground (transparent)
  mipmap-<density>/ic_launcher_monochrome.png  themed-icon layer (Android 13+)
  drawable/ic_launcher_background.xml          solid black
and app/src/main/ic_launcher-playstore.png (512x512, for the Play Console).

Usage:  python3 mkandroidicons.py [--project ~/AndroidStudioProjects/pa] [--dry-run]
"""

import argparse
import os
import re
import struct
import sys

from PIL import Image, ImageDraw

HOME = os.path.expanduser("~")
ICON_CPP = os.path.join(HOME, "programming/CPP-New/va/icon_voltaic.cpp")

# Launcher icon densities. Legacy icons are 48dp, adaptive layers are 108dp.
DENSITIES = {
    "mdpi": 1.0,
    "hdpi": 1.5,
    "xhdpi": 2.0,
    "xxhdpi": 3.0,
    "xxxhdpi": 4.0,
}
LEGACY_DP = 48
ADAPTIVE_DP = 108

# How much of the canvas the mark's ink (glow included) spans.
#
# Legacy icons are shown whole, so the mark sits at its natural proportions --
# the 512 source already carries ~6% margin.
LEGACY_INK = 0.88
# Adaptive foregrounds keep only the central 72dp of the 108dp canvas, and a
# circular mask keeps only a 66dp circle inside that.
#
# Size this against the CORE's half-DIAGONAL, not against its width. The V's two
# widest points are its arm tips, and they sit at the TOP -- so their distance
# from centre is sqrt(dx^2+dy^2), not dx. Sizing by width put the core at 57dp,
# which looks safe inside a 66dp circle but lands the tips at radius 37 > 33 and
# visibly clips them. Core half-diagonal is 194.8 source px; holding that to
# ~31dp (33 minus margin) gives an ink span of 0.66 and a ~47dp core, which is
# the weight a launcher glyph wants. The remaining glow tapers out under the
# mask edge, which is invisible at <10% alpha.
ADAPTIVE_INK = 0.66

BACKGROUND_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- VOLTAIC launcher background. Flat black: the house convention is the mark on
     an opaque black square (matches the web icon set and the app itself), and a
     glowing mark needs an unlit field behind it to read. Generated by
     pa-iplug/scripts/mkandroidicons.py; regenerate rather than hand-editing.
     (No double-hyphens in here: aapt rejects them inside an XML comment.) -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h108v108h-108z" />
</vector>
"""


def load_baked_mark():
    """Decode the PNG out of the uint32 array in icon_voltaic.cpp."""
    src = open(ICON_CPP).read()
    m = re.search(r"icon_size\s*=\s*(\d+)", src)
    if not m:
        sys.exit(f"could not find icon_size in {ICON_CPP}")
    size = int(m.group(1))
    body = src.split("{", 1)[1].rsplit("}", 1)[0]
    words = [int(w, 16) for w in re.findall(r"0x([0-9a-fA-F]+)", body)]
    data = b"".join(struct.pack("<I", w) for w in words)[:size]
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        sys.exit("decoded bytes are not a PNG -- has the array format changed?")
    import io
    return Image.open(io.BytesIO(data)).convert("RGBA")


def ink_bbox(img, threshold=5):
    """Bounding box of everything with meaningful alpha, glow included."""
    alpha = img.split()[3]
    return alpha.point(lambda a: 255 if a > threshold else 0).getbbox()


def place(mark, canvas_px, ink_fraction):
    """Centre the mark on a transparent canvas, ink spanning `ink_fraction`."""
    box = ink_bbox(mark)
    ink = mark.crop(box)
    scale = (canvas_px * ink_fraction) / max(ink.width, ink.height)
    w, h = max(1, round(ink.width * scale)), max(1, round(ink.height * scale))
    ink = ink.resize((w, h), Image.LANCZOS)
    out = Image.new("RGBA", (canvas_px, canvas_px), (0, 0, 0, 0))
    out.paste(ink, ((canvas_px - w) // 2, (canvas_px - h) // 2), ink)
    return out


def on_black(layer):
    bg = Image.new("RGBA", layer.size, (0, 0, 0, 255))
    return Image.alpha_composite(bg, layer)


def circle_masked(img):
    mask = Image.new("L", img.size, 0)
    ImageDraw.Draw(mask).ellipse((0, 0, img.size[0] - 1, img.size[1] - 1), fill=255)
    out = img.copy()
    out.putalpha(mask)
    return out


def monochrome(layer):
    """Themed-icon layer: a flat silhouette the launcher tints itself.

    Built from luminance, not alpha: the mark's alpha includes its wide soft
    glow, and a tinted blob of glow reads as a smudge. Luminance isolates the
    white core, i.e. the actual V stroke.
    """
    px = layer.load()
    out = Image.new("RGBA", layer.size, (0, 0, 0, 0))
    op = out.load()
    for y in range(layer.size[1]):
        for x in range(layer.size[0]):
            r, g, b, a = px[x, y]
            lum = (0.3 * r + 0.6 * g + 0.1 * b) / 255.0 * (a / 255.0)
            # Soft ramp rather than a hard threshold, so the stroke keeps clean
            # antialiased edges at mdpi. The floor has to sit ABOVE the glow's
            # luminance (~0.3-0.5) or the silhouette fattens into the halo and
            # the themed icon reads as a blob instead of a V.
            v = max(0.0, min(1.0, (lum - 0.58) / 0.28))
            op[x, y] = (0, 0, 0, int(round(v * 255)))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default=os.path.join(HOME, "AndroidStudioProjects/pa"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    res = os.path.join(args.project, "app/src/main/res")
    if not os.path.isdir(res):
        sys.exit(f"no res/ directory at {res}")

    mark = load_baked_mark()
    print(f"mark {mark.size[0]}x{mark.size[1]} ink bbox {ink_bbox(mark)}")

    written = []

    def save(img, path):
        written.append(path)
        if not args.dry_run:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            img.save(path)

    for density, factor in DENSITIES.items():
        legacy_px = round(LEGACY_DP * factor)
        adaptive_px = round(ADAPTIVE_DP * factor)
        d = os.path.join(res, f"mipmap-{density}")

        square = on_black(place(mark, legacy_px, LEGACY_INK))
        save(square, os.path.join(d, "ic_launcher.png"))
        save(circle_masked(square), os.path.join(d, "ic_launcher_round.png"))

        fg = place(mark, adaptive_px, ADAPTIVE_INK)
        save(fg, os.path.join(d, "ic_launcher_foreground.png"))
        save(monochrome(fg), os.path.join(d, "ic_launcher_monochrome.png"))

    save(on_black(place(mark, 512, LEGACY_INK)),
         os.path.join(args.project, "app/src/main/ic_launcher-playstore.png"))

    bg_path = os.path.join(res, "drawable/ic_launcher_background.xml")
    written.append(bg_path)
    if not args.dry_run:
        open(bg_path, "w").write(BACKGROUND_XML)

    for p in written:
        print(("would write " if args.dry_run else "wrote ") + os.path.relpath(p, args.project))


if __name__ == "__main__":
    main()
